// <auto-generated />
using System;
using CertManager.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrations.Postgresql.Migrations
{
    [DbContext(typeof(CertManagerContext))]
    partial class CertManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertManager.DAL.Certificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CertificateId");

                    b.HasIndex("CertificateName")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("CertManager.DAL.CertificateTag", b =>
                {
                    b.Property<Guid>("CertificateTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CertificateTagId");

                    b.HasIndex("CertificateId");

                    b.ToTable("CertificateTags");
                });

            modelBuilder.Entity("CertManager.DAL.CertificateVersion", b =>
                {
                    b.Property<Guid>("CertificateVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cn")
                        .IsRequired()
                        .HasMaxLength(442)
                        .HasColumnType("character varying(442)")
                        .HasColumnName("CN");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasMaxLength(442)
                        .HasColumnType("character varying(442)");

                    b.Property<byte[]>("RawCertificate")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("CertificateVersionId");

                    b.HasIndex("CertificateId");

                    b.ToTable("CertificateVersions");
                });

            modelBuilder.Entity("CertManager.DAL.CertificateTag", b =>
                {
                    b.HasOne("CertManager.DAL.Certificate", "Certificate")
                        .WithMany("CertificateTags")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertManager.DAL.CertificateVersion", b =>
                {
                    b.HasOne("CertManager.DAL.Certificate", "Certificate")
                        .WithMany("CertificateVersions")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertManager.DAL.Certificate", b =>
                {
                    b.Navigation("CertificateTags");

                    b.Navigation("CertificateVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
