branches: 
  - main

tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
      - type: "build"
        release: patch
      - type: "refactor"
        release: patch
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
      - "path": "native-binaries/*"
      - "path": "migration.sql"
  - - "@semantic-release-plus/docker"
    - name: "ghcr.io/desmaraisp/cert-manager:latest"
  - - "@semantic-release-plus/docker"
    - name: "ghcr.io/desmaraisp/cert-manager-agent:latest"