version: "3.2"

services:
  sql-server-db:
    image: sql-server-db
    build:
      context: DevelopmentDatabase/.
    ports:
      - 1433:1433
  sql-server-migrations:
    image: sql-server-migrations
    command: ["--connection", "Data Source=sql-server-db\\MSSQLSERVER,1433;TrustServerCertificate=True;User Id=SA;Password=Change_this_password10", "--", "--provider", "SqlServer"]
    depends_on:
      sql-server-db:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/CertManager/Dockerfile.migrations
      args:
        provider: SqlServer
  keycloak-local:
    image: quay.io/keycloak/keycloak:20.0
    command: ["start-dev"]
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
        interval: 10s
        timeout: 5s
        retries: 10
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    ports:
      - 8080:8080
  tf:
    depends_on:
      keycloak-local:
        condition: service_healthy
    image: terraform
    build:
      context: .
      dockerfile: terraform-local/Dockerfile
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
