name: Run Unit tests

on:
  workflow_call: 
  pull_request: 

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Unit tests
        run: dotnet test

      - name: restore tools
        run: dotnet tool restore

      - name: check if migrations up-to-date
        run: |
          dotnet ef migrations has-pending-model-changes --project ./src/CertManager/CertManager.csproj -- --provider Postgresql
          dotnet ef migrations has-pending-model-changes --project ./src/CertManager/CertManager.csproj -- --provider SqlServer

      - name: build image
        run: |
          docker build -f ./src/CertManager/Dockerfile -t "certmanager:latest" .

      - name: check if swagger doc is up to date
        shell: pwsh
        run: |
          docker run -e ASPNETCORE_ENVIRONMENT=Development -d -p 5156:5156 certmanager
          ./dev-scripts/refresh-openapi.ps1

          $status = $(git status --short)
          if(-not $status){
            echo "Working directory clean, swagger is up-to-date"
          }
          else {
            echo "Working directory not clean, swagger is not up-to-date"
            exit 1
          }
